function varargout = validatelengtharray(lengthArray,nElements,varargin)
%VALIDATELENGTHARRAY Validate a lengtharray.

[varargout{1:nargout}] = validateattributes( ...
    lengthArray, ...
    {'numeric'}, ...
    {'real','finite','nonnan','nonsparse','nonempty','positive','row','vector','numel',nElements}, ...
    varargin{:});

end

