function obj = subdivide(obj,subdivisionLevel)
% Validate input.
validateattributes( ...
    subdivisionLevel, ...
    {'numeric'}, ...
    {'real','finite','nonnan','nonsparse','nonempty','scalar','integer','>=',0});

if subdivisionLevel > 1
    [obj.vertices,obj.faces] = ...
        subdivideMesh(obj.vertices,obj.faces,subdivisionLevel);
end
end