function obj = rotatearoundaxis(obj,axisDirection,angleDegree)

% Validate inputs
validateattributes( ...
    axisDirection, ...
    {'numeric'}, ...
    {'real','finite','nonnan','nonsparse','nonempty','row','vector','numel',3});

validateattributes( ...
    angleDegree, ...
    {'numeric'}, ...
    {'real','finite','nonnan','nonsparse','nonempty','scalar'});


for child = obj.children
    child.mesh = child.mesh.rotatearoundaxis(axisDirection,angleDegree,obj.centerOfMass);
end
end